<?php /* @var $block \Auctane\Api\Block\System\Config\GenerateApiKeyButton */ ?>
<script>
  require([
    'jquery',
  ], function (jQuery) {
    jQuery('#generate_and_save_api_key').on('click', function () {
        return new Ajax.Request("<?= $escaper->escapeUrl($block->getApiKeyGenerationUrl()) ?>", {
            loaderArea: true,
            asynchronous: true,
            onSuccess: function (response) {
                let data = JSON.parse(response.responseText);
                jQuery('#shipstation_general_shipstation_ship_api_key').val(data.key);
            }
        })
    })
  })
</script>

<?= $block->getButtonHtml() ?>
