name: Move Code to Auctane Directory

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker
    - name: Run Docker
      uses: addnab/docker-run-action@v3
      with:
        image: markoshust/magento-php:8.3-fpm-2
        options: -v ${{ github.workspace }}:/var/www/html/src/app/code/Auctane
        run: |
          composer require --dev magento/magento-coding-standard
          composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer install
          vendor/bin/phpcs --standard=Magento2 --report=junit /var/www/html/src/app/code/Auctane
