on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Run CodeSniffer in Docker
    - name: Generate CodeSniffer Report
      continue-on-error: true
      run: |
        docker run --rm \
          --user $(id -u):$(id -g) \
          -v ${{ github.workspace }}:/var/www/html/src/app/code/Auctane \
          markoshust/magento-php:8.3-fpm-2 \
          bash -c "
            cd /var/www/html/src/app/code/Auctane/Api &&
            cp composer.json composer.json.bak &&
            sed -i 's/\"registration.php\"//' composer.json &&
            composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true &&
            composer require --dev magento/magento-coding-standard &&
            vendor/bin/phpcs --standard=Magento2 --report=checkstyle --report-file=phpcs-report.xml /var/www/html/src/app/code/Auctane/Api || true &&
            mv composer.json.bak composer.json
          "

    # Step 3: Annotate PR with violations
    - name: Annotate Code Issues
      if: always()
      run: |
        if [ -f Api/phpcs-report.xml ]; then
          cat Api/phpcs-report.xml | cs2pr --graceful-warnings
        fi